// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.18.1
// source: coordinator/coordinator.proto

package coordinator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionCoordinator_StartTransaction_FullMethodName = "/coordinator.TransactionCoordinator/StartTransaction"
)

// TransactionCoordinatorClient is the client API for TransactionCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionCoordinatorClient interface {
	StartTransaction(ctx context.Context, in *StartTransactionRequest, opts ...grpc.CallOption) (*StartTransactionResponse, error)
}

type transactionCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionCoordinatorClient(cc grpc.ClientConnInterface) TransactionCoordinatorClient {
	return &transactionCoordinatorClient{cc}
}

func (c *transactionCoordinatorClient) StartTransaction(ctx context.Context, in *StartTransactionRequest, opts ...grpc.CallOption) (*StartTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTransactionResponse)
	err := c.cc.Invoke(ctx, TransactionCoordinator_StartTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionCoordinatorServer is the server API for TransactionCoordinator service.
// All implementations must embed UnimplementedTransactionCoordinatorServer
// for forward compatibility.
type TransactionCoordinatorServer interface {
	StartTransaction(context.Context, *StartTransactionRequest) (*StartTransactionResponse, error)
	mustEmbedUnimplementedTransactionCoordinatorServer()
}

// UnimplementedTransactionCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionCoordinatorServer struct{}

func (UnimplementedTransactionCoordinatorServer) StartTransaction(context.Context, *StartTransactionRequest) (*StartTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTransaction not implemented")
}
func (UnimplementedTransactionCoordinatorServer) mustEmbedUnimplementedTransactionCoordinatorServer() {
}
func (UnimplementedTransactionCoordinatorServer) testEmbeddedByValue() {}

// UnsafeTransactionCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionCoordinatorServer will
// result in compilation errors.
type UnsafeTransactionCoordinatorServer interface {
	mustEmbedUnimplementedTransactionCoordinatorServer()
}

func RegisterTransactionCoordinatorServer(s grpc.ServiceRegistrar, srv TransactionCoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedTransactionCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionCoordinator_ServiceDesc, srv)
}

func _TransactionCoordinator_StartTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionCoordinatorServer).StartTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionCoordinator_StartTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionCoordinatorServer).StartTransaction(ctx, req.(*StartTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionCoordinator_ServiceDesc is the grpc.ServiceDesc for TransactionCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.TransactionCoordinator",
	HandlerType: (*TransactionCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTransaction",
			Handler:    _TransactionCoordinator_StartTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator/coordinator.proto",
}
